apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bounty-ingress
  namespace: tongagent
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: bounty-server-lb
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: bounty.tongagents.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bounty-server-lb
                port:
                  number: 4005
